name:                loading
version:             0.1.0.0
github:              "githubuser/loading"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/loading#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  include-dirs:
    - src
  c-sources:
    - src\haskell.cpp
  extra-libraries:
    - stdc++
  ghc-options:
    - -pgmccl

executables:
  loading-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - loading

tests:
  loading-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - loading
